# Generated by Django 4.1.7 on 2023-04-28 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_veiculo_tabela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='tabela',
        ),
    ]
